type MealType = 'breakfast' | 'lunch' | 'dinner'
type ProgramType = 'lose' | 'maintain' | 'gain'

export interface ExtendedRecipe {
  id: number
  nameUk: string
  prepTime: string
  calories: number
  protein: number
  fat: number
  carbs: number
  balanceScore: number
  emoji: string
  mealTypes: MealType[]
  programs: ProgramType[]
  ingredients: Array<{ name: string; quantity: string }>
  steps: string[]
  description: string
  photo?: string
  tagsUk: string[]
}

export const EXTENDED_RECIPES: ExtendedRecipe[] = [
  // BREAKFAST
  {
    id: 101,
    nameUk: 'Сирники ніжні та пухкі',
    emoji: '🥞',
    prepTime: '20 хв',
    calories: 350,
    protein: 20,
    fat: 16,
    carbs: 35,
    balanceScore: 88,
    mealTypes: ['breakfast'],
    programs: ['maintain', 'gain'],
    description: 'Ніжні та пухкі сирники з творогу - класичний український сніданок',
    tagsUk: ['Цей творог', 'Класика', 'Швидко'],
    ingredients: [
      { name: 'Творог', quantity: '200 г' },
      { name: 'Яйце', quantity: '1 шт' },
      { name: 'Цукор', quantity: '1 ст. л.' },
      { name: 'Мука', quantity: '3 ст. л.' },
      { name: 'Олія кокосова', quantity: '1 ст. л.' },
    ],
    steps: [
      'Відділіть жовток від білка',
      'У творог додайте жовток, цукор та перемішайте',
      'Добавте борошно та перемішайте',
      'Белок збийте в піну та обережно вмішайте',
      'Розігрійте олію на сковороді',
      'Жарте сирники по 3-4 хв з кожної сторони',
    ],
  },
  {
    id: 102,
    nameUk: 'Омлет із сиром та овочами',
    emoji: '🍳',
    prepTime: '15 хв',
    calories: 380,
    protein: 26,
    fat: 25,
    carbs: 12,
    balanceScore: 90,
    mealTypes: ['breakfast'],
    programs: ['maintain', 'gain'],
    description: 'Пухкий омлет з твердим сиром та свіжими овочами',
    tagsUk: ['Білки', 'Овочі', 'Швидко'],
    ingredients: [
      { name: 'Яйця', quantity: '2 шт' },
      { name: 'Молоко', quantity: '40 мл' },
      { name: 'Сир твердий', quantity: '30 г' },
      { name: 'Помідори чері', quantity: '5-6 шт' },
      { name: 'Шпинат', quantity: '30 г' },
      { name: 'Олія оливкова', quantity: '1 ст. л.' },
    ],
    steps: [
      'Збийте яйця з молоком та сіллю',
      'Розігрійте олію на сковороді',
      'Додайте шпинат і помідори',
      'Вилийте суміш яєць',
      'Натріть сир поверх омлету',
      'Готуйте 3-4 хвилини до готовності',
    ],
  },
  {
    id: 103,
    nameUk: 'Вівсяна каша з йогуртом та ягодами',
    emoji: '🥣',
    prepTime: '10 хв',
    calories: 380,
    protein: 22,
    fat: 10,
    carbs: 50,
    balanceScore: 92,
    mealTypes: ['breakfast'],
    programs: ['lose', 'maintain'],
    description: 'Збалансована каша з грецьким йогуртом та свіжими ягодами',
    tagsUk: ['Клітковина', 'Антиоксиданти', 'Швидко'],
    ingredients: [
      { name: 'Вівсяні пластівці', quantity: '50 г' },
      { name: 'Молоко', quantity: '150 мл' },
      { name: 'Вода', quantity: '100 мл' },
      { name: 'Йогурт грецький', quantity: '100 г' },
      { name: 'Ягоди змішані', quantity: '100 г' },
      { name: 'Мед', quantity: '10 г' },
    ],
    steps: [
      'Вскипятите воду та молоко',
      'Додайте вівсяні пластівці та готуйте 5 хв',
      'Перелийте в миску',
      'Додайте йогурт та ягоди',
      'Полийте медом та подавайте',
    ],
  },

  // LUNCH
  {
    id: 201,
    nameUk: 'Паста карбонара',
    emoji: '🍝',
    prepTime: '25 хв',
    calories: 650,
    protein: 30,
    fat: 32,
    carbs: 55,
    balanceScore: 85,
    mealTypes: ['lunch', 'dinner'],
    programs: ['maintain', 'gain'],
    description: 'Класична італійська паста карбонара з беконом та вершками',
    tagsUk: ['Італійська кухня', 'Білки', 'Калорійна'],
    ingredients: [
      { name: 'Спагеті', quantity: '80 г' },
      { name: 'Бекон копчений', quantity: '100 г' },
      { name: 'Вершки 35%', quantity: '50 мл' },
      { name: 'Яйце', quantity: '1 шт' },
      { name: 'Пармезан', quantity: '30 г' },
    ],
    steps: [
      'Вскипятите воду та вихідну пасту',
      'Нарізьте бекон та обсмажте 3-4 хв',
      'Збийте яйце без білків з вершками',
      'Откиньте пасту, залишивши трохи води',
      'Додайте креманту суміш та перемішайте',
      'Посипте пармезаном',
    ],
  },
  {
    id: 202,
    nameUk: 'Курка теріякі з рисом та броколі',
    emoji: '🍗',
    prepTime: '25 хв',
    calories: 620,
    protein: 38,
    fat: 18,
    carbs: 75,
    balanceScore: 92,
    mealTypes: ['lunch', 'dinner'],
    programs: ['maintain', 'gain'],
    description: 'Куряче філе в терияки соусі з рисом та броколі',
    tagsUk: ['Азійська кухня', 'Білки', 'Повільні вуглеводи'],
    ingredients: [
      { name: 'Філе куриное', quantity: '150 г' },
      { name: 'Рис басматі', quantity: '70 г' },
      { name: 'Броколі', quantity: '150 г' },
      { name: 'Соус теріякі', quantity: '30 г' },
      { name: 'Кунжут', quantity: '5 г' },
    ],
    steps: [
      'Звари рис згідно інструкції на пакованні',
      'Нарізьте філе на шматки',
      'Обсмажте курку на олії 5-6 хв',
      'Додайте соус теріякі та готуйте 3 хв',
      'Заготуйте броколі на пару',
      'Подавайте разом на тарілці',
    ],
  },
  {
    id: 203,
    nameUk: 'Яловичина, тушкована з гречкою та овочами',
    emoji: '🥓',
    prepTime: '30 хв',
    calories: 620,
    protein: 40,
    fat: 22,
    carbs: 50,
    balanceScore: 90,
    mealTypes: ['lunch', 'dinner'],
    programs: ['maintain', 'gain'],
    description: 'Ніжна яловичина, тушкована з гречкою та овочами',
    tagsUk: ['Яловичина', 'Гречка', 'Ситна'],
    ingredients: [
      { name: 'Яловичина', quantity: '150 г' },
      { name: 'Гречка', quantity: '70 г' },
      { name: 'Морква', quantity: '70 г' },
      { name: 'Цибуля', quantity: '50 г' },
      { name: 'Паста томатна', quantity: '20 г' },
      { name: 'Вода', quantity: '200 мл' },
    ],
    steps: [
      'Нарізьте яловичину на шматки',
      'Обсмажте на олії 5 хв',
      'Додайте нарізану цибулю та морквю',
      'Додайте пасту томатну та вода',
      'Готуйте 15-20 хв до м\'якості',
      'Подавайте з гречкою',
    ],
  },

  // DINNER
  {
    id: 301,
    nameUk: 'Теплий салат з куркою',
    emoji: '🥗',
    prepTime: '20 хв',
    calories: 480,
    protein: 35,
    fat: 20,
    carbs: 25,
    balanceScore: 94,
    mealTypes: ['dinner'],
    programs: ['lose', 'maintain'],
    description: 'Легкий теплий салат з курою та авокадо',
    tagsUk: ['Легкий', 'Білки', 'Авокадо'],
    ingredients: [
      { name: 'Філе куриное', quantity: '130 г' },
      { name: 'Авокадо', quantity: '50 г' },
      { name: 'Помідори', quantity: '100 г' },
      { name: 'Латук', quantity: '50 г' },
      { name: 'Олія оливкова', quantity: '2 ст. л.' },
      { name: 'Лимон', quantity: '1/2 шт' },
    ],
    steps: [
      'Обсмажте філе на гарячій сковороді 8-10 хв',
      'Нарізьте на шматки',
      'Порвіть латук на частини',
      'Нарізьте помідори та авокадо',
      'Змішайте все в миску',
      'Полейте лимонним соком та олією',
    ],
  },
  {
    id: 302,
    nameUk: 'Запечена риба з овочами та йогуртовим соусом',
    emoji: '🐟',
    prepTime: '25 хв',
    calories: 480,
    protein: 35,
    fat: 20,
    carbs: 25,
    balanceScore: 96,
    mealTypes: ['dinner'],
    programs: ['lose', 'maintain'],
    description: 'Ніжна запечена риба з овочами та йогуртовим соусом',
    tagsUk: ['Риба', 'Омега-3', 'Легка'],
    ingredients: [
      { name: 'Філе хека/тріски', quantity: '180 г' },
      { name: 'Кабачок', quantity: '150 г' },
      { name: 'Болгарський перець', quantity: '100 г' },
      { name: 'Йогурт грецький', quantity: '100 г' },
      { name: 'Олія оливкова', quantity: '1 ст. л.' },
    ],
    steps: [
      'Розігрійте духовку до 180°C',
      'Нарізьте кабачок та перець соломкою',
      'Покладіть на противень',
      'Покладіть філе риби зверху',
      'Запікайте 15 хв',
      'Приготуйте соус з йогурту та подавайте',
    ],
  },
  {
    id: 303,
    nameUk: 'Запечені котлети з індички + салат',
    emoji: '🍖',
    prepTime: '25 хв',
    calories: 480,
    protein: 38,
    fat: 18,
    carbs: 50,
    balanceScore: 88,
    mealTypes: ['dinner'],
    programs: ['lose', 'maintain'],
    description: 'Запечені котлети з індички з овощевим салатом',
    tagsUk: ['Індичка', 'Легка мясо', 'Запечені'],
    ingredients: [
      { name: 'Фарш індичка', quantity: '180 г' },
      { name: 'Яйце', quantity: '0.5 шт' },
      { name: 'Цибуля', quantity: '30 г' },
      { name: 'Огірок', quantity: '150 г' },
      { name: 'Помідор', quantity: '100 г' },
      { name: 'Латук', quantity: '50 г' },
    ],
    steps: [
      'Змішайте фарш, яйце та дрібно нарізану цибулю',
      'Сформуйте котлети',
      'Покладіть на противень з пергаментом',
      'Запікайте 15-20 хв при 180°C',
      'Нарізьте овочі для салату',
      'Подавайте котлети з овощевим салатом',
    ],
  },
]
