import type { Recipe } from '@/types'

export const RECIPES: Recipe[] = [
  {
    id: 'borsch',
    name: 'Ukrainian Borsch',
    nameUk: 'Борщ Український',
    description: 'Classic Ukrainian beet soup with cabbage, potatoes and pork',
    prepTime: 30,
    cookTime: 90,
    servings: 6,
    cuisine: 'ukrainian',
    tags: ['soup', 'traditional', 'hearty'],
    ingredients: [
      { name: 'Буряк', quantity: 0.4, unit: 'кг', category: 'produce' },
      { name: 'Капуста', quantity: 0.5, unit: 'кг', category: 'produce' },
      { name: 'Картопля', quantity: 0.4, unit: 'кг', category: 'produce' },
      { name: 'Морква', quantity: 0.2, unit: 'кг', category: 'produce' },
      { name: 'Цибуля', quantity: 0.2, unit: 'кг', category: 'produce' },
      { name: 'Томатна паста', quantity: 70, unit: 'г', category: 'grocery' },
      { name: 'Свинина (ребра)', quantity: 0.5, unit: 'кг', category: 'meat' },
      { name: 'Сметана', quantity: 200, unit: 'г', category: 'dairy' },
      { name: 'Часник', quantity: 30, unit: 'г', category: 'produce' },
    ],
    instructions: [
      'Зварити бульйон зі свинини (40 хв)',
      'Нарізати й обсмажити буряк, моркву, цибулю',
      'Додати томатну пасту, тушкувати 10 хв',
      'У бульйон додати капусту й картоплю',
      'Через 15 хв додати засмажку та часник',
      'Варити ще 10 хв, подавати зі сметаною',
    ],
    calories: 280,
  },
  {
    id: 'varenyky',
    name: 'Varenyky with Potato',
    nameUk: 'Вареники з картоплею',
    description: 'Traditional Ukrainian dumplings with potato and onion filling',
    prepTime: 60,
    cookTime: 20,
    servings: 4,
    cuisine: 'ukrainian',
    tags: ['dumplings', 'traditional', 'vegetarian'],
    ingredients: [
      { name: 'Борошно', quantity: 400, unit: 'г', category: 'grocery' },
      { name: 'Яйце', quantity: 60, unit: 'г', category: 'dairy' },
      { name: 'Картопля', quantity: 0.5, unit: 'кг', category: 'produce' },
      { name: 'Цибуля', quantity: 0.2, unit: 'кг', category: 'produce' },
      { name: 'Вершкове масло', quantity: 50, unit: 'г', category: 'dairy' },
      { name: 'Сметана', quantity: 150, unit: 'г', category: 'dairy' },
    ],
    instructions: [
      'Замісити тісто з борошна, яйця, солі та води',
      'Зварити картоплю, розтовкти з маслом',
      'Обсмажити цибулю, змішати з картоплею',
      'Розкачати тісто, вирізати кружечки',
      'Зліпити вареники з начинкою',
      'Варити 5-7 хв у підсоленій воді',
      'Подавати зі сметаною та шкварками',
    ],
    calories: 320,
  },
  {
    id: 'chicken-kyiv',
    name: 'Chicken Kyiv',
    nameUk: 'Котлета по-київськи',
    description: 'Crispy fried chicken breast stuffed with herb butter',
    prepTime: 40,
    cookTime: 25,
    servings: 2,
    cuisine: 'ukrainian',
    tags: ['chicken', 'fried', 'classic'],
    ingredients: [
      { name: 'Куряче філе', quantity: 0.5, unit: 'кг', category: 'meat' },
      { name: 'Вершкове масло', quantity: 100, unit: 'г', category: 'dairy' },
      { name: 'Кріп', quantity: 30, unit: 'г', category: 'produce' },
      { name: 'Часник', quantity: 20, unit: 'г', category: 'produce' },
      { name: 'Яйце', quantity: 120, unit: 'г', category: 'dairy' },
      { name: 'Панірувальні сухарі', quantity: 100, unit: 'г', category: 'grocery' },
      { name: 'Борошно', quantity: 50, unit: 'г', category: 'grocery' },
      { name: 'Олія соняшникова', quantity: 200, unit: 'мл', category: 'grocery' },
    ],
    instructions: [
      'Змішати масло з кропом і часником, заморозити',
      'Відбити куряче філе до рівномірної товщини',
      'Загорнути замерзле масло у філе, сформувати котлету',
      'Запанірувати: борошно → яйце → сухарі → яйце → сухарі',
      'Смажити у фритюрі 15 хв при 180°С',
      'Допекти у духовці 10 хв при 180°С',
    ],
    calories: 520,
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal with Berries',
    nameUk: 'Вівсянка з ягодами',
    description: 'Creamy oatmeal topped with fresh or frozen berries and honey',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    cuisine: 'universal',
    tags: ['breakfast', 'healthy', 'quick'],
    ingredients: [
      { name: 'Вівсяні пластівці', quantity: 200, unit: 'г', category: 'grocery' },
      { name: 'Молоко', quantity: 400, unit: 'мл', category: 'dairy' },
      { name: 'Ягоди заморожені', quantity: 150, unit: 'г', category: 'frozen' },
      { name: 'Мед', quantity: 60, unit: 'г', category: 'grocery' },
      { name: 'Банан', quantity: 0.2, unit: 'кг', category: 'produce' },
    ],
    instructions: [
      'Довести молоко до кипіння',
      'Додати вівсянку, варити 5 хв помішуючи',
      'Розкласти по тарілках',
      'Прикрасити ягодами, бананом та медом',
    ],
    calories: 340,
  },
  {
    id: 'pasta-bolognese',
    name: 'Pasta Bolognese',
    nameUk: 'Паста Болоньєзе',
    description: 'Classic Italian meat sauce with spaghetti',
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    cuisine: 'italian',
    tags: ['pasta', 'meat', 'italian'],
    ingredients: [
      { name: 'Спагеті', quantity: 400, unit: 'г', category: 'grocery' },
      { name: 'Фарш яловичий', quantity: 500, unit: 'г', category: 'meat' },
      { name: 'Томати консервовані', quantity: 400, unit: 'г', category: 'grocery' },
      { name: 'Цибуля', quantity: 0.15, unit: 'кг', category: 'produce' },
      { name: 'Морква', quantity: 0.15, unit: 'кг', category: 'produce' },
      { name: 'Часник', quantity: 20, unit: 'г', category: 'produce' },
      { name: 'Оливкова олія', quantity: 50, unit: 'мл', category: 'grocery' },
      { name: 'Пармезан', quantity: 50, unit: 'г', category: 'dairy' },
    ],
    instructions: [
      'Обсмажити цибулю, моркву, часник на оливковій олії',
      'Додати фарш, смажити до готовності',
      'Додати томати, тушкувати 30 хв',
      'Зварити спагеті al dente',
      'Змішати пасту з соусом',
      'Подавати з тертим пармезаном',
    ],
    calories: 480,
  },
  {
    id: 'greek-salad',
    name: 'Greek Salad',
    nameUk: 'Грецький салат',
    description: 'Fresh salad with feta, olives and crisp vegetables',
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    cuisine: 'mediterranean',
    tags: ['salad', 'vegetarian', 'quick', 'healthy'],
    ingredients: [
      { name: 'Помідори', quantity: 0.3, unit: 'кг', category: 'produce' },
      { name: 'Огірок', quantity: 0.2, unit: 'кг', category: 'produce' },
      { name: 'Перець болгарський', quantity: 0.15, unit: 'кг', category: 'produce' },
      { name: 'Цибуля червона', quantity: 0.1, unit: 'кг', category: 'produce' },
      { name: 'Оливки', quantity: 100, unit: 'г', category: 'grocery' },
      { name: 'Сир Фета', quantity: 150, unit: 'г', category: 'dairy' },
      { name: 'Оливкова олія', quantity: 50, unit: 'мл', category: 'grocery' },
      { name: 'Орегано', quantity: 5, unit: 'г', category: 'grocery' },
    ],
    instructions: [
      'Нарізати всі овочі великими шматками',
      'Змішати у салатнику',
      'Зверху викласти шматочки фети',
      'Додати оливки',
      'Полити оливковою олією, посипати орегано',
    ],
    calories: 280,
  },
  {
    id: 'scrambled-eggs',
    name: 'Scrambled Eggs with Vegetables',
    nameUk: 'Яєчня з овочами',
    description: 'Fluffy eggs with sautéed peppers, tomatoes and herbs',
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    cuisine: 'universal',
    tags: ['breakfast', 'eggs', 'quick', 'protein'],
    ingredients: [
      { name: 'Яйце', quantity: 240, unit: 'г', category: 'dairy' },
      { name: 'Помідор', quantity: 0.15, unit: 'кг', category: 'produce' },
      { name: 'Перець болгарський', quantity: 0.1, unit: 'кг', category: 'produce' },
      { name: 'Вершкове масло', quantity: 20, unit: 'г', category: 'dairy' },
      { name: 'Зелень', quantity: 30, unit: 'г', category: 'produce' },
    ],
    instructions: [
      'Нарізати овочі дрібними кубиками',
      'Обсмажити на вершковому маслі 3 хв',
      'Збити яйця, вилити на сковороду',
      'Помішуючи, готувати до бажаної консистенції',
      'Посипати зеленню, подавати одразу',
    ],
    calories: 220,
  },
  {
    id: 'chicken-soup',
    name: 'Chicken Noodle Soup',
    nameUk: 'Курячий суп з локшиною',
    description: 'Comforting homestyle chicken soup with vegetables and noodles',
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    cuisine: 'universal',
    tags: ['soup', 'chicken', 'comforting'],
    ingredients: [
      { name: 'Куряче філе', quantity: 0.5, unit: 'кг', category: 'meat' },
      { name: 'Локшина яєчна', quantity: 200, unit: 'г', category: 'grocery' },
      { name: 'Морква', quantity: 0.2, unit: 'кг', category: 'produce' },
      { name: 'Цибуля', quantity: 0.15, unit: 'кг', category: 'produce' },
      { name: 'Картопля', quantity: 0.3, unit: 'кг', category: 'produce' },
      { name: 'Лавровий лист', quantity: 5, unit: 'г', category: 'grocery' },
      { name: 'Зелень', quantity: 30, unit: 'г', category: 'produce' },
    ],
    instructions: [
      'Зварити курку у 2л води (40 хв)',
      'Дістати курку, розібрати на шматки',
      'У бульйон додати картоплю, моркву, цибулю',
      'Через 15 хв додати локшину та курку',
      'Варити ще 10 хв',
      'Подавати з рубаною зеленню',
    ],
    calories: 240,
  },
]

export const CUISINE_OPTIONS = [
  { value: 'ukrainian', label: '🇺🇦 Українська' },
  { value: 'italian',   label: '🇮🇹 Італійська' },
  { value: 'asian',     label: '🥢 Азійська' },
  { value: 'mediterranean', label: '🫒 Середземноморська' },
  { value: 'universal', label: '🌍 Інтернаціональна' },
]

export const DIETARY_OPTIONS = [
  { value: 'vegetarian',  label: '🌱 Вегетаріанська' },
  { value: 'vegan',       label: '🥗 Веганська' },
  { value: 'gluten-free', label: '🌾 Без глютену' },
  { value: 'dairy-free',  label: '🥛 Без лактози' },
  { value: 'halal',       label: '☪️ Халяль' },
]